Iter9
Kopleman/metcol pull request #11
Opened 2024-12-20 20:42 UTC by Kopleman

2024-12-24 13:17 UTC, s-shpak requested changes

2024-12-24 13:17 UTC, s-shpak commented on cmd/server/main.go
> +			logger.Fatal(err)
Кажется, что здесь достаточно залогировать ошибку: процесс и так уже завершается, завершать его насильно кажется излишним

2024-12-24 13:17 UTC, s-shpak commented on cmd/server/main.go
> +			logger.Fatal(err)
Нельзя фаталиться из глубины кода, здесь тоже достаточно логирования

2024-12-24 13:17 UTC, s-shpak commented on internal/server/file_storage/file_storage.go
> +	stats, err := fs.file.Stat()
Так проверять существование файла нет смысла: между этой проверкой и использованием файла, файл может быть удален. Лучше просто используй файл и проверяй возвращаемую ошибку

2024-12-24 13:17 UTC, s-shpak commented on internal/common/utils.go
> +func Pointer[T any](v T) *T {
Эта функция используется только в тестах, так что лучше перенести ее в пакет с тестами. Кроме того, можно обойтись и без нее: в тест-кейсе передавай конкретное значение, а внутри самого теста бери адрес этого значения

2024-12-24 20:50 UTC, s-shpak requested changes

2024-12-24 20:50 UTC, s-shpak commented on internal/agent/metrics-collector/metrics_collector.go
> +			go mc.doIntervalJobs(&args, quit)
Не надо запускать горутину на каждый тик таймера, запусти воркеров один раз, пусть они отправляют запросы, но их количество будет органичено

2024-12-24 20:50 UTC, s-shpak commented on internal/common/http-client/http_client.go
> +	defer gz.Close() //nolint:all // defer
Тут ошибку можно залогировать при помощи анонимной функции

2024-12-24 21:50 UTC, Kopleman commented on internal/agent/metrics-collector/metrics_collector.go
> +			go mc.doIntervalJobs(&args, quit)
Не очень понимаю. Но горутину убрал

2024-12-27 12:52 UTC, s-shpak approved these changes

2024-12-27 15:14 UTC, merged