Iter5
Kopleman/metcol pull request #7
Opened 2024-11-27 14:07 UTC by Kopleman

2024-11-29 12:04 UTC, s-shpak requested changes
1. Я не отмечаю все однотипные ошибки/замечания, исправь повторяющиеся проблемы самостоятельно, пожалуйста.

2. Любые вопросы по комментариям можно и нужно задавать в общем канале пачки

3. Добавь в проект линтер `golangci-lint`. Здесь объясняется как это сделать: https://github.com/s-shpak/praktikum-golangci-lint . Также добавь его проверки в `Github Actions` и исправь все замечания, пожалуйста

4. Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

2024-11-29 12:04 UTC, s-shpak commented on cmd/agent/main.go
> +func main() {
Постарайся оставлять в `main.go` (и в пакете `main`) как можно меньше логики: там могут лежать только создание и настройка компонентов и запуск сервиса. Всю остальную логику нужно перенести в `internal`.

2024-11-29 12:04 UTC, s-shpak commented on internal/common/flags/net-address.go
> +type NetAddress struct {
Я бы не парсил строку с адресом сервера, а запускал ее ровно так, как она передана пользователем. Если пользователь ошибся, то отправить запрос просто не получится. Но если ты все же решишь парсить строку, то я рекомендую использовать `https://pkg.go.dev/net/url#Parse`

2024-11-29 12:04 UTC, s-shpak commented on cmd/agent/main.go
> +			fmt.Println(fmt.Printf("collected metrics at %s", time.Now().UTC()))
1. Ты можешь написать так:

```suggestion
			fmt.Printf("collected metrics at %s\n", time.Now().UTC())
```

2. Не используй пакет `fmt`, вместо него используй `log`. В дальнейшем мы перейдем либо на `slog`, либо на сторонний линтер типа `zap`.

2024-11-29 12:04 UTC, s-shpak commented on cmd/server/main.go
> +		panic(err)
Паниковать не надо: используй `log.Fatal` для:
    1. вывода ошибки
    2. завершения процесса с ошибкой

2024-11-29 12:04 UTC, s-shpak commented on cmd/agent/main.go
> +	collectTimer := now.Add(pollDuration)
В стандартной библиотеке Go в пакете `time` есть структура `Tikcer` (https://pkg.go.dev/time#Ticker), которая очень хорошо подходит для решения этой задачи. Я советую тебе использовать ее или обертку над ней (https://pkg.go.dev/time#Tick) в связке с `select`-`case` для периодической отправки метрик с агента.

2024-11-29 12:04 UTC, s-shpak commented on internal/agent/config/config.go
> +		panic(err)
1. См. комментарий про панику выше
2. Вызов `log.Fatal` здесь завершит процесс. Не стоит делать это из глубины кода: лучше прокинуть ошибку наверх, т.к. возможно наверху мы сможем ее обработать. Если подходящего обработчика нет, то ошибка должна дойти до точки входа, спровоцировать graceful shutdown приложения и, после, завершение процесса.

2024-11-29 12:04 UTC, s-shpak commented on internal/agent/config/config.go
> +	if cfgFromEnv.PollInterval > 0 {
Не усложняй логику здесь: если ты хочешь провалидировать полученные значения, то лучше сделать это отдельно. Тем более тогда надо проверить и значения полученные через флаги

2024-11-29 12:04 UTC, s-shpak commented on internal/agent/metrics-collector/errors.go
> +var ErrCounterPollParse = errors.New("unable to parse counterpoll value")
Зачем объявлена эта ошибка ? Ошибки в Go лучше объявлять, если они где-то обрабатываются дальше (то есть ты "ловишь" их при помощи `errors.Is()`), в ином случае смысла объявлять новую переменную-ошибку нет

2024-11-29 12:04 UTC, s-shpak commented on internal/agent/metrics-collector/metrics_collector.go
> +		return ErrCounterPollParse
В ошибки лучше добавляють контекст: например, текст, объясняющий, что именно пошло не так и где

2024-11-29 12:04 UTC, s-shpak commented on internal/agent/metrics-collector/metrics_collector.go
> +		return err
Ошибки из сторонних пакетов надо оборачивать при помощи `fmt.Errorf` и `%w`. Здесь смотри подробнее как: https://go.dev/blog/go1.13-errors#wrapping-errors-with-w

2024-11-29 12:04 UTC, s-shpak commented on internal/agent/metrics-collector/metrics_collector.go
> +		value:      strconv.FormatUint(mem.Alloc, 10),
Хранить значения в строке кажется нелогичным: тебе надо конвертировать их в число каждый раз. Можно ли хранить их сразу в численном виде ?

2024-11-29 12:04 UTC, s-shpak commented on internal/agent/metrics-collector/metrics_collector.go
> +func (mc *MetricsCollector) increasePollCounter() error {
Сейчас это работает некорректно: счетчик увеличивается при каждом сборе метрика на 1, а сервер прибалвяет полученное значение к пердыдущему. Вот пример того, что может произойти:

- агент собрал метрики 3 раза и отправляет серверу это значение
- сервер сохраняет его
- агент собрал метрики еще 2 раза и отправляет серверу значение 5 (3 + 2)
- сервер прибавляет его к предыдущему. С т.з. сервера агент произвел 8 сборов метрик

Подумай, как это исправить

2024-11-29 12:04 UTC, s-shpak commented on internal/common/http-client/http_client.go
> +type IHTTPClient interface {
1. В Go интерфейсы не принято называть с заглавной `I`. Это может быть просто `HTTPClient`
2. В Go интрефейсы принято объявлять там, где они используются. Посмотри вебинар, там мы это подробно обсуждали

2024-11-29 12:04 UTC, s-shpak commented on internal/common/http-client/http_client.go
> +		err = errors.Join(err, res.Body.Close())
Не стоит так джоинить ошибки. Если ты хочешь, чтобы она точно была возвращена, то просто оберни ее в ошибку при помощи `fmt.Errorf`. В принципе, такую ошибку достаточно залогировать

2024-11-29 12:04 UTC, s-shpak commented on internal/metrics/metrics.go
> +	if err != nil && !errors.Is(err, store.ErrNotFound) {
Так код будет проще читать:

```suggestion
	if err != nil {
	    if errors.Is(err, store.ErrNotFound) {
	        ...
	        return
	    }
	    ...
	    return
	}
```

2024-11-29 12:04 UTC, s-shpak commented on internal/server/controllers/get_value.go
> +			http.Error(w, err.Error(), http.StatusInternalServerError)
1. Штатные ошибки (т.е. те ошибки, которые приводят к ответу клиенту с кодом 4**) не нужно логировать: они произошли "по вине" клиента и будут только замусоривать лог. А вот ошибки 5** нужно логировать обязательно
2. В случае нештатной ошибки, нельзя посылать детали о ней пользователю, т.к. это угроза безопасности приложения.

2024-11-29 12:04 UTC, s-shpak commented on internal/server/middlewares/post_filter.go
> +func PostFilterMiddleware(next http.Handler) http.Handler {
Т.к. ты используешь `chi`, этот код не нужен

2024-11-29 12:04 UTC, s-shpak commented on internal/server/routers/server.go
> +	controllers2 "github.com/Kopleman/metcol/internal/server/controllers"
Зачем этот alias ?

2024-11-29 14:20 UTC, Kopleman commented on internal/common/flags/net-address.go
> +type NetAddress struct {
Парсинг строк это требование автотестов как минимум

2024-11-29 15:17 UTC, Kopleman commented on internal/agent/config/config.go
> +	if cfgFromEnv.PollInterval > 0 {
вот тут не понял: там же прям условие - 
Приоритет параметров должен быть таким:
Если указана переменная окружения, то используется она.
Если нет переменной окружения, но есть аргумент командной строки (флаг), то используется он.
Если нет ни переменной окружения, ни флага, то используется значение по умолчанию.

То есть у нас может быть комбинация например: PollInterval в енвах, адрес через флаг и репорт интервал вообще забыли

2024-11-29 15:23 UTC, Kopleman commented on internal/agent/metrics-collector/metrics_collector.go
> +		value:      strconv.FormatUint(mem.Alloc, 10),
Не понял, мне значение вставлять потом в урл - `url := "/update/" + string(item.metricType) + "/" + name + "/" + item.value`, то есть все равно приводить к строке

2024-11-29 16:12 UTC, Kopleman commented on internal/server/routers/server.go
> +	controllers2 "github.com/Kopleman/metcol/internal/server/controllers"
Это goldand что то выдал)

2024-11-29 16:29 UTC, Kopleman commented on internal/server/middlewares/post_filter.go
> +func PostFilterMiddleware(next http.Handler) http.Handler {
Без него не проходит автотесты 2 инкремента

2024-11-30 14:02 UTC, s-shpak commented on cmd/agent/main.go
> +		return err
Ошибки, которые приходят из сторонних пакетов лучше оборачивать:

```suggestion
		return fmt.Errorf("failed to parse the agent's config: %w", err)
```

2024-11-30 14:02 UTC, s-shpak commented on internal/common/flags/net-address.go
> +type NetAddress struct {
То есть если убрать парсинг условного `localhost:8080`, то автотесты развалятся ?

2024-11-30 14:09 UTC, s-shpak commented on internal/agent/metrics-collector/metrics_collector.go
> +			go mc.doIntervalJobs(&args, quit)
Не надо запускать новую горутину на каждый тик: это чревато тем, что если `doIntervalJobs` станет медленной, то количество горутин будет постоянно расти, и это, по сути, будет утечкой памяти. Лучше просто выполняй все действия синхронно

2024-11-30 14:09 UTC, s-shpak commented on internal/agent/config/config.go
> +	if cfgFromEnv.PollInterval > 0 {
Все так, но я про валидацию, т.е. проверку на `PollInterval > 0`.

С моей т.з. лучше сделать так, если ты хочешь валидировать конфигурацию:
1. сначала получить конфиг по указаным правилам приоритета
2. потом завалидировать установленные значения

Если клиент использовал невалидное значение при настройке агента, то лучше сказать ему об этом, выкинув ошибку, чем использовать другое значение без дополнительной информации: так поведение агента будет более ожидаемым.

Ну и, кроме всего, ты не валидируешь значение, полученное из флага

2024-11-30 14:16 UTC, s-shpak requested changes
Дай мне, пожалуйста, права контрибьютора в репозитории, чтобы я мог резолвить комментарии, которые поправлены.

2024-11-30 14:16 UTC, s-shpak commented on internal/agent/metrics-collector/metrics_collector.go
> +		value:      strconv.FormatUint(mem.Alloc, 10),
Да, соглсен, здесь выигрыш не очень большой, но, хотя бы, сокртаится количество кода. Но, в принципе, это делать необязательно, если ты решишь не делать, то просто зарезолвь этот комментарий

2024-11-30 14:16 UTC, s-shpak commented on internal/agent/metrics-collector/metrics_collector.go
> +		return errors.New("unable to parse counterpoll value on poll counter inc")
Сюда также можно записать, какое именно значение не получилось распарсить

2024-11-30 14:16 UTC, s-shpak commented on internal/common/http-client/http_client.go
> +		c.logger.Error(err)
Если `err == nil`, то ничего логировать не надо

2024-11-30 16:57 UTC, Kopleman commented on internal/agent/metrics-collector/metrics_collector.go
> +		value:      strconv.FormatUint(mem.Alloc, 10),
а в чем сокращение кода и его упрощение ? У меня 2(сейчас) типа float и int. Я на месте его парсю и превращаю в строку что бы. В противном случае нужно либо 2 поля, или 2 разных сущности. И все равно потом горидить логику где надо описать  как конкретное число привести к строке.

2024-11-30 17:28 UTC, Kopleman commented on internal/common/flags/net-address.go
> +type NetAddress struct {
Чет я перегнул, да не было там такого, накрутил лишнего функционала. Убрать?

2024-11-30 17:43 UTC, Kopleman commented on internal/agent/config/config.go
> +	if cfgFromEnv.PollInterval > 0 {
так я что то запутался.  Сейчас у меня оно же так и работает: так как у меня указатель передается для флагов, то сперва мы парсим флаги. Потом парсим значения с енвов, и если там не пустые значения, мы их записываем в конфиг - так как у них выше приоритет.

p.s. добавил чуть валидации

2024-12-02 14:55 UTC, s-shpak requested changes
1. ты пока не добавил меня в контрибуторы, сделай это, пожалуйста
2. добавь `golangci-lint` в github actions: https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions

2024-12-02 14:55 UTC, s-shpak commented on internal/agent/config/config.go
> +	if cfgFromEnv.PollInterval > 0 {
Я имел в виду, что если ты хочешь валидировать значения, то лучше делать это, разделив их получения и валидацию:

```go
...
cfg, err := getConfig()
if err := validateConfig(cfg); err != nil {
    return fmt.Errorf("configuration is invalid: %w", err)
...
```

Тогда конфиг будет получен по правилам приоритета, после чего полученное значение будет провалидировано. Кажется, что такой вариант наиболее удобен для пользователя

2024-12-02 14:55 UTC, s-shpak commented on internal/common/flags/net-address.go
> +type NetAddress struct {
В принципе, необязательно, просто из моего опыта такие проверки, как правило, выстрелят в какой-то момент в ногу, потому что какой-то валидный формат они принимать не будут.

Такие проверки обычно делаются через `url.Parse`, если они нужный. Я не против, чтобы ты ее оставил, но, мне кажется, что лучший код -- ненаписанный, потому я бы просто передавал через конфиг сырую `url`, и если она невалидна, то сервер просто не запустится

2024-12-03 22:25 UTC, s-shpak requested changes

2024-12-03 22:25 UTC, s-shpak commented on internal/common/log/logger.go
>  type Logger interface {
А зачем этот интерфейс логгера ? Почему не использовать `zap` напрямую ?

2024-12-04 06:59 UTC, Kopleman commented on internal/common/log/logger.go
>  type Logger interface {
это же обертка, я ее не много там подчистил,  после копи-паста. Но в оригинале он там более накручен. Ну и к тому же упрощает чуть инициализаю.

2024-12-04 07:18 UTC, Kopleman commented
Ты можешь как то по резволвить коменты,  и отдеблно оставить только то что надо попраить? А то у меня все уже перемешалось в кучу просто

2024-12-04 20:30 UTC, s-shpak approved these changes

2024-12-04 21:10 UTC, merged